### ISSUE TITLE
latest build broken

### ISSUE THREAD

**Issue by tromp** [google/highwayhash#27]
dear Jan,

trying to build the latest version:

$ make all
g++ -std=c++11 -O3 -mavx2 -Wall -I.   -c -o highwayhash/os_specific.o highwayhash/os_specific.cc
highwayhash/os_specific.cc:1:61: fatal error: third_party/highwayhash/highwayhash/os_specific.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'highwayhash/os_specific.o' failed
make: *** [highwayhash/os_specific.o] Error 1

Btw, defining uint64 in a less portable way "for interoperability with TensorFlow"
seems like a missed opportunity to fix what looks like a bug in TensorFlow :-(
Now the need for using the less portable long long type extends to all users of highwayhash...

regards,
-John

**Comment by jan-wassenberg** [comment]
Hi John, thanks for reporting this :)
Is it an option to let your highwayhash/highwayhash/ reside in a directory called third_party? If so, it should work now that I've updated the Makefile.

FYI we had to change the include paths because -isystem is quite costly for Bazel. It would be nice if we can keep the source code the same internally and in Github.

I agree uint64 is unfortunate. This definition is quite old and unfortunately much more frequently used in our code than uint64_t. Changing it would be a major undertaking, but I am quietly hopeful we'll do it some day :)

**Comment by tromp** [comment]
dear Jan,

It still fails with the new Makefile:

...
Updating 6c32c9f..be6156e
Fast-forward
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
$ make all
g++ -std=c++11 -O3 -mavx2 -Wall -I../..   -c -o highwayhash/os_specific.o highwayhash/os_specific.cc
highwayhash/os_specific.cc:1:61: fatal error: third_party/highwayhash/highwayhash/os_specific.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'highwayhash/os_specific.o' failed
make: *** [highwayhash/os_specific.o] Error 1

I don't see how changing directory names above this repo would help.
Currently the repo sits right in my homedir, so the file in question is
/home/tromp/highwayhash/highwayhash/os_specific.h
while the Makefile looks for
third_party/highwayhash/highwayhash/os_specific.h

regards,
-John

**Comment by jan-wassenberg** [comment]
Hi John,
would it be an option to move the repository to /home/tromp/**third_party**/highwayhash/highwayhash/ ?
Then, /home/tromp/ is on the include path and we can pick up third_party/highwayhash/highwayhash/*.h from there.

**Comment by tromp** [comment]
dear Jan,

yeah, that works.
But it's the strangest requirement ever to assume a directory name containing a git-repo :-(

Btw, my reason for using highway hash is that I designed the Cuckoo Cycle proof-of-work, at
https://github.com/tromp/cuckoo/
which is based on siphash-2-4, and wanted it to spend less time on hashing,
(and hence more on memory latency).
Previously it was computing siphash one at a time, using the code in src/siphash.h,
so I thought doing 4 at a time should give about a 4x speedup on just the hashing.

But initial tests show just a 17% reduction in hashing speed, which I'm still struggling to explain:
$ make hash28
$ time ./hash28 -m 1
...
real    0m7.874s

$ make hash28avx2
$ time ./hash28avx2 -m 1
...
real    0m6.586s

Option -DHASHONLY still does some other work besides the hashing, but it should be pretty minimal.
I'll add separate hash-only source when I get around to it...

regards,
-John

**Comment by jan-wassenberg** [comment]
It is admittedly unusual - do you have an idea how we could keep the source code identical between the internal/external repository and avoid sed scripts in both directions? I suppose we could ```#define''' the header names, but that's also ugly.

Very interesting application, I enjoyed reading your blog, thanks!

FYI we have also observed that an SSE4.1 version of SipHash is actually slower than scalar code. Very likely cause: AVX2 lacks bit rotate instructions, so we need shift+shift+OR instead of a single ROL.
The SipTreeHash is also only 2x faster instead of 4x.

**Comment by tromp** [comment]
dear Jan,

> It is admittedly unusual - do you have an idea how we could keep the source code identical between the internal/external repository and avoid sed scripts in both directions? I suppose we could ```#define''' the header names, but that's also ugly.

I don't understand how your internal repo differs.
When you have
#include "third_party/highwayhash/ ...
in a source file, doesn't that file reside in a "highwayhash" directory?

> Very interesting application, I enjoyed reading your blog, thanks!

You're welcome!

> FYI we have also observed that an SSE4.1 version of SipHash is actually slower than scalar code. Very likely cause: AVX2 lacks bit rotate instructions, so we need shift+shift+OR instead of a single ROL.

A siphash round does 6 ROTL's but 3 of them are short-aligned and
thus can be replaced by short-permutations.
I can see that this prevents a 4x speedup, but I'd still expect around 3x.
What I got is less than 1.4x :-(

regards,
-John

**Comment by tromp** [comment]
I left some accidental noinline attribute in cuckoo.h distorting the above hash only times.
Here are the corrected numbers:

$ time ./hash_only hash
sum 8017e0b5
real	0m7.846s

$ time ./hash_only_avx2
sum 8017e0b5
real	0m11.029s

In other words, the AVX2 4-way version is actually 40% slower!

I also made myself an 8-way version, and that one finally catches up:
$ time ./hash_only_avx2 # compiled with -DWP=8
sum 8017e0b5
real	0m7.426s

Btw, the 1-way version using plain uint64's also combines left and right shifts to rotate,
and doesn't get the shortcuts for 16/32 bit rotates, so I'm still rather puzzled as to
why the AVX2 versions perform so poorly...

**Comment by jan-wassenberg** [comment]
Hi John,

> I don't understand how your internal repo differs.
> When you have #include "third_party/highwayhash/ ...
> in a source file, doesn't that file reside in a "highwayhash" directory?
It does, but our paths are absolute. The workspace root contains a "third_party" folder within which highwayhash resides. In other words, the include path is actually the full path from workspace root to the header.

> In other words, the AVX2 4-way version is actually 40% slower!
Ouch! But yes, we also observed scalar code was faster.

> Btw, the 1-way version using plain uint64's also combines left and right shifts to rotate,
> and doesn't get the shortcuts for 16/32 bit rotates, so I'm still rather puzzled as to
> why the AVX2 versions perform so poorly...
Interesting. Are you sure the generated code lacks ROTL? Compilers can recognize the two shifts and replace with ROTL.

**Comment by tromp** [comment]
dear Jan,

> I don't understand how your internal repo differs.
> When you have #include "third_party/highwayhash/ ...
> in a source file, doesn't that file reside in a "highwayhash" directory?
> It does, but our paths are absolute.

The why not make them relative? Why would need to step out of the
highwayhash directory?

> In other words, the AVX2 4-way version is actually 40% slower!

> Ouch! But yes, we also observed scalar code was faster.

It takes more effort to catch up.with avx2. If you check my latest
cuckoo commit, you can see that siphash.h, in addtion to the 1-way
siphash2x, also has 4-way, 8-way, and 18-way versions, the latter two
using multiple interleaved 4-way ones.
For pure hashing, I get times
hashonly        7.87
hashonlyx4   10.78
hashonlyx8    7.42
hashonlyx16  7.61

So it takes 2x interleaving on top of 4way avx2 to come out ahead,
and more interleaving doesn't help.
When plugging these into cuckoo, we get some surprising results:
cuckoo28st     10.04
cuckoo28stx4    8.08
cuckoo28stx8    7.38
cuckoo28stx16  8.72
Suddenly, the 4-way changes from a big loss into a big win!
Not surprisingly, 8-way is even better and 16x is still worse.

> Btw, the 1-way version using plain uint64's also combines left and right shifts to rotate,
> and doesn't get the shortcuts for 16/32 bit rotates, so I'm still rather puzzled as to
> why the AVX2 versions perform so poorly...
> Interesting. Are you sure the generated code lacks ROTL? Compilers can recognize the two shifts and replace with ROTL.

Good point. I just checked in gdb (layout split is awesome),
and indeed it uses lots of rorx instructions.

regards,
-John

**Comment by jan-wassenberg** [comment]
> The why not make them relative? Why would need to step out of the highwayhash directory?

The Bazel build system generally uses absolute paths. I think the original rationale involved some symlinks in the root directory.

Interesting measurements. I'm surprised how much performance varies. Looks like an interaction between running out of architectural regs and spilling to stack, versus better execution unit utilization (probably not latency hiding because these are all single-cycle operations).

> indeed it uses lots of rorx instructions.

Good to know, thanks for checking!

**Comment by tromp** [comment]
dear Jan,

> The Bazel build system generally uses absolute paths. I think the original rationale involved some symlinks in the root directory.

Looks like Bazel needs a little github-friendliness love :-)

> Interesting measurements. I'm surprised how much performance varies. Looks like an interaction between running out of architectural regs and spilling to stack, versus better execution unit utilization (probably not latency hiding because these are all single-cycle operations).

Any idea how to test for these hypotheses?

regards,
-John

**Comment by jan-wassenberg** [comment]
> Any idea how to test for these hypotheses?

I'd just look at the generated code and note how many memory accesses (spills) there are in the various versions.

Will be on the road until next Fri and slower to reply. Have a good one!

**Comment by tromp** [comment]
dear Jan,

>> Interesting measurements. I'm surprised how much performance varies. Looks like an interaction between running out of architectural regs and spilling to stack, versus better execution unit utilization (probably not latency hiding because these are all single-cycle operations).
>
> Any idea how to test for these hypotheses?

There's no spilling that I can see, except with the 16-way siphash,
where ymm15 is occasionally written to and read back from the stack.
But the 4-way and 8-way siphash never spill...

regards,
-John

**Comment by jan-wassenberg** [comment]
huh, that's surprising. Some more ideas: unlucky prefetch strides (always difficult.. might also try normal loads instead of prefetch), unaligned branch targets, larger code exceeding the uop cache capacity.

**Comment by jan-wassenberg** [comment]
I believe this issue is resolved, please feel free to reopen if needed.
